module.exports = {
  mode: "jit",
  purge: {
    // Learn more on https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
    enabled: process.env.NODE_ENV === "production",
    content: [
      "./public/index.html",
      "./src/**/*.html",
      "./src/**/*.vue",
      "./src/styles/**/*.css",
    ],
  },
  darkMode: "class", // or 'media' or 'class'
  prefix: "tw-",
  theme: {
    fontFamily: {
      ClashDisplay: ["ClashDisplay", "system-ui"],
      "ClashDisplay-normal": ["ClashDisplay Normal", "system-ui"],
      "ClashDisplay-medium": ["ClashDisplay Medium", "system-ui"],
      "ClashDisplay-semibold": ["ClashDisplay Semibold", "system-ui"],
      "ClashDisplay-bold": ["ClashDisplay Bold", "system-ui"],
    },
    extend: {
      colors: {
        transparent: "transparent",
        primary: { DEFAULT: "#0E6B56", white: "#ffffff" },
        secondary: { DEFAULT: "#001140", dark: "#001E70", light: "#06206B" },
        error: { DEFAULT: "#EB5757", light: "#F5D5CB" },
        success: { DEFAULT: "#27AE60", light: "#D7ECD9", lightest: "#E2F8EB" },
        warning: { DEFAULT: "#E2B93B" },
        lemon: { DEFAULT: "#EBFFF4" },
        info: { DEFAULT: "#2F80ED", light: "#B3E0FF" },
        orange: { DEFAULT: "#C06C00", dark: "#694521", lightest: "#FFF5EA" },
        pastel3: { DEFAULT: "#E5EDFF" },
        gray: {
          DEFAULT: "#8F8F8F",
          dark: "#231F20",
          bg1: "#FAFAFA",
          bg2: "#E7E7E8",
          bg3: "#FBFBFB",
          bg4: "#F5F5F5",
          bg5: "#F4F4F4",
          bg6: "#F9FAF9",
        },
        orange: {
          DEFAULT: "#FF861D",
          dark: "#80430F",
          bg1: "#FFEBD9",
          bg2: "#FFF8F0",
          bg3: "#FFF7F0",
          bg4: "#FFFBF8",
          bg5: "#FDF6EE",
          bg6: "#FFEFE1",
        },
        green: {
          DEFAULT: "#0E6B56",
          lemon: "#9EE86F",
          bg1: "#68AB74",
          bg2: "#F2FFF5",
          bg3: "#C7EDB1",
          bg4: "#003130",
          bg5: "#ECFAE3",
          bg6: "#F9FDF5",
          bg7: "#E5EFEC",
          bg8: "#F7FCF3",
          bg9: "#05241D",
          bg10: "#F0FBE8",
          bg11: "#B5DBB7",
        },
        red: {
          DEFAULT: "#cd1750",
          error: "#DB4343",
          "error-pink": "#FCE9E9",
        },
        pink: {
          light: "#ff7ce5",
          DEFAULT: "#ff49db",
          dark: "#ff16d1",
        },
        black: {
          dark: "#1A2139",
          DEFAULT: "#020B27",
          light: "#4F5877",
          lightest: "#ffffff",
        },
        purple: {
          light: "#4C5B90",
        },
      },
      outline: {
        primary: "1px solid #4D84FF",
      },
      zIndex: {
        "-10": "-10",
      },
    },
    screens: {
      xxxs: "320px",
      xxs: "375px",
      xs: "425px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      xxl: "1440px",
      xxxl: "1536px",
      xxxxl: "1900px",
    },
  },
  variants: {
    extend: {
      opacity: ["disabled"],
      cursor: ["disabled"],
      text: ["disabled"],
      display: ["group-hover"],
    },
  },
  plugins: [],
};
